package report

import (
	"fmt"
	"html"
	"strings"
	"time"
)

// dashboardCSS is the stylesheet shared by the repository and organization
// dashboards: GitHub dark theme, matching the ODS PR report.
const dashboardCSS = `<style>
  :root { --bg:#0d1117; --panel:#161b22; --border:#30363d; --fg:#c9d1d9; --muted:#8b949e;
          --fg-strong:#f0f6fc; --ai:#a371f7; --human:#30363d; --accent:#58a6ff; }
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
         max-width: 860px; margin: 0 auto; padding: 40px 20px; color: var(--fg); background: var(--bg);
         line-height: 1.55; }
  a { color: var(--accent); text-decoration: none; }
  header { border-bottom: 1px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }
  header h1 { font-size: 1.4em; color: var(--fg-strong); margin: 0 0 4px; }
  header .sub { color: var(--muted); font-size: .9em; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 12px; margin-bottom: 28px; }
  .card { background: var(--panel); border: 1px solid var(--border); border-radius: 8px; padding: 16px 18px; }
  .card .label { color: var(--muted); font-size: .78em; text-transform: uppercase; letter-spacing: .04em; }
  .card .value { font-size: 2em; font-weight: 700; color: var(--fg-strong); margin-top: 6px; line-height: 1.1; }
  .card.hero .value { color: var(--ai); }
  .card .sub { color: var(--muted); font-size: .82em; margin-top: 4px; }
  .section { margin: 28px 0; }
  .section h2 { font-size: 1.05em; color: var(--fg-strong); border-bottom: 1px solid var(--border);
                padding-bottom: 8px; margin-bottom: 16px; }
  .legend { font-size: .82em; color: var(--muted); margin-bottom: 10px; }
  .legend .dot { display:inline-block; width:10px; height:10px; border-radius:2px; margin:0 4px 0 14px; vertical-align: middle; }
  .legend .dot:first-child { margin-left: 0; }
  .chart-wrap { overflow-x: auto; }
  .tool-row { display: flex; align-items: center; gap: 10px; margin: 8px 0; font-size: .9em; }
  .tool-name { width: 180px; color: var(--fg-strong); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .tool-bar-track { flex: 1; background: var(--panel); border: 1px solid var(--border); border-radius: 999px; height: 12px; overflow: hidden; }
  .tool-bar-fill { background: var(--ai); height: 100%; }
  .tool-count { width: 64px; text-align: right; color: var(--muted); font-variant-numeric: tabular-nums; }
  footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid var(--border); color: var(--muted); font-size: .82em; }
</style>
<style>
  table.repos { border-collapse: collapse; width: 100%; font-size: .9em; }
  table.repos th, table.repos td { padding: 8px 10px; text-align: left; border-bottom: 1px solid var(--border); vertical-align: middle; }
  table.repos th { color: var(--fg-strong); font-weight: 600; background: var(--panel); }
  table.repos td.num, table.repos th.num { text-align: right; font-variant-numeric: tabular-nums; }
  table.repos .share { display: inline-block; min-width: 46px; }
  table.repos .bar { display: inline-block; width: 90px; height: 8px; background: var(--panel); border: 1px solid var(--border); border-radius: 999px; overflow: hidden; vertical-align: middle; margin-left: 8px; }
  table.repos .bar span { display: block; height: 100%; background: var(--ai); }
</style>`

// dashboardHead opens a dashboard document: doctype, the shared stylesheet
// and the page header. subtitle is HTML (callers escape their dynamic parts).
func dashboardHead(title, subtitle string) string {
	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>` + html.EscapeString(title) + `</title>
` + dashboardCSS + `
</head>
<body>
<header>
  <h1>` + html.EscapeString(title) + `</h1>
  <div class="sub">` + subtitle + `</div>
</header>
`
}

// dashboardFoot closes a dashboard document. The attribution note is left off
// the empty-state page, which has nothing to qualify.
func dashboardFoot(generated string, withNote bool) string {
	note := ""
	if withNote {
		note = ` · Attribution reflects what AI tools disclose, not forensic detection.`
	}
	return `<footer>Generated by <a href="https://github.com/open-delivery-spec">Open Delivery Spec</a> · ` + generated + note + `</footer>
</body></html>`
}

// trendSection renders the AI-share-over-time chart, or nothing without data.
func trendSection(buckets []TimeBucket) string {
	if len(buckets) == 0 {
		return ""
	}
	return `<div class="section"><h2>AI share over time</h2>
<div class="legend"><span class="dot" style="background:var(--ai)"></span>AI-assisted<span class="dot" style="background:var(--human)"></span>human</div>
<div class="chart-wrap">` + renderTrendSVG(buckets) + `</div></div>
`
}

// toolSection renders the per-tool bars, widest bar for the busiest tool.
func toolSection(tools []ToolCount) string {
	if len(tools) == 0 {
		return ""
	}
	var b strings.Builder
	maxN := tools[0].Commits
	b.WriteString(`<div class="section"><h2>By tool</h2>`)
	for _, tc := range tools {
		w := 0.0
		if maxN > 0 {
			w = float64(tc.Commits) / float64(maxN) * 100
		}
		fmt.Fprintf(&b, `<div class="tool-row"><span class="tool-name">%s</span><span class="tool-bar-track"><span class="tool-bar-fill" style="width:%.0f%%"></span></span><span class="tool-count">%d</span></div>
`, html.EscapeString(tc.Tool), w, tc.Commits)
	}
	b.WriteString(`</div>
`)
	return b.String()
}

// RenderHTML renders a self-contained, shareable dashboard for the report.
// No external assets — inline CSS and an inline SVG trend chart — so the file
// opens offline and screenshots cleanly. The palette matches the ODS PR report
// (GitHub dark theme) for one visual identity across the toolchain.
func RenderHTML(r Report, generatedAt time.Time) string {
	var b strings.Builder

	aiPct := fmt.Sprintf("%.0f%%", r.AICommitShare*100)
	linePct := fmt.Sprintf("%.0f%%", r.AILineShare*100)
	generated := generatedAt.UTC().Format("2006-01-02 15:04 UTC")

	b.WriteString(dashboardHead("ODS AI Attribution Report",
		"Since "+html.EscapeString(r.Since)+" · attribution from Co-Authored-By / Assisted-by trailers"))

	if r.TotalCommits == 0 {
		b.WriteString(`<p class="sub">No commits in the selected window.</p>
` + dashboardFoot(generated, false))
		return b.String()
	}

	// Hero cards.
	fmt.Fprintf(&b, `<div class="cards">
  <div class="card hero"><div class="label">AI commit share</div><div class="value">%s</div><div class="sub">%d of %d commits</div></div>
  <div class="card hero"><div class="label">AI line share</div><div class="value">%s</div><div class="sub">%d of %d changed lines</div></div>
  <div class="card"><div class="label">Commits</div><div class="value">%d</div><div class="sub">%d human · %d AI-assisted</div></div>
  <div class="card"><div class="label">Changed lines</div><div class="value">%s</div><div class="sub">across the window</div></div>
</div>
`, aiPct, r.AICommits, r.TotalCommits,
		linePct, r.AIChangedLines, r.TotalChangedLines,
		r.TotalCommits, r.HumanCommits, r.AICommits,
		humanizeInt(r.TotalChangedLines))

	b.WriteString(trendSection(r.Buckets))
	b.WriteString(toolSection(r.ToolBreakdown()))
	b.WriteString(dashboardFoot(generated, true))
	return b.String()
}

// renderTrendSVG draws stacked bars (AI portion + human portion) per time
// bucket. Bar height encodes commit volume; the accent fill encodes AI share.
func renderTrendSVG(buckets []TimeBucket) string {
	const (
		barW   = 26
		gap    = 10
		plotH  = 200
		padTop = 12
		padBot = 34 // room for x labels
		padL   = 8
	)
	maxCommits := 1
	for _, bk := range buckets {
		if bk.TotalCommits > maxCommits {
			maxCommits = bk.TotalCommits
		}
	}
	width := padL*2 + len(buckets)*barW + (len(buckets)-1)*gap
	if width < 320 {
		width = 320
	}
	height := plotH + padTop + padBot

	var b strings.Builder
	fmt.Fprintf(&b, `<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" role="img" aria-label="AI commit share over time" font-family="-apple-system,Segoe UI,Helvetica,Arial,sans-serif">`, width, height)
	// baseline
	fmt.Fprintf(&b, `<line x1="0" y1="%d" x2="%d" y2="%d" stroke="#30363d"/>`, padTop+plotH, width, padTop+plotH)

	// Label every bucket when few, otherwise thin out to ~8 labels.
	step := 1
	if len(buckets) > 10 {
		step = (len(buckets) + 7) / 8
	}
	for i, bk := range buckets {
		x := padL + i*(barW+gap)
		totalH := int(float64(bk.TotalCommits) / float64(maxCommits) * float64(plotH))
		if totalH < 2 && bk.TotalCommits > 0 {
			totalH = 2
		}
		aiH := 0
		if bk.TotalCommits > 0 {
			aiH = int(float64(bk.AICommits) / float64(bk.TotalCommits) * float64(totalH))
		}
		yTop := padTop + plotH - totalH
		yAI := padTop + plotH - aiH
		// human portion (full bar background)
		fmt.Fprintf(&b, `<rect x="%d" y="%d" width="%d" height="%d" rx="2" fill="#30363d"><title>%s: %d commits, %.0f%% AI</title></rect>`,
			x, yTop, barW, totalH, html.EscapeString(bk.Label), bk.TotalCommits, bk.AIShare*100)
		// AI portion (bottom)
		if aiH > 0 {
			fmt.Fprintf(&b, `<rect x="%d" y="%d" width="%d" height="%d" rx="2" fill="#a371f7"/>`, x, yAI, barW, aiH)
		}
		// share % above bar
		if bk.TotalCommits > 0 {
			fmt.Fprintf(&b, `<text x="%d" y="%d" text-anchor="middle" font-size="9" fill="#8b949e">%.0f%%</text>`,
				x+barW/2, yTop-4, bk.AIShare*100)
		}
		// x label
		if i%step == 0 {
			fmt.Fprintf(&b, `<text x="%d" y="%d" text-anchor="middle" font-size="9" fill="#8b949e">%s</text>`,
				x+barW/2, padTop+plotH+16, html.EscapeString(shortLabel(bk.Label)))
		}
	}
	b.WriteString(`</svg>`)
	return b.String()
}

// shortLabel trims a bucket label for the x-axis (e.g. "2026-W28" -> "W28").
func shortLabel(label string) string {
	if i := strings.Index(label, "-W"); i >= 0 {
		return label[i+1:]
	}
	if i := strings.Index(label, "-"); i >= 0 {
		return label[i+1:] // "2026-07" -> "07"
	}
	return label
}

// humanizeInt formats an int with thousands separators.
func humanizeInt(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var parts []string
	for len(s) > 3 {
		parts = append([]string{s[len(s)-3:]}, parts...)
		s = s[:len(s)-3]
	}
	parts = append([]string{s}, parts...)
	return strings.Join(parts, ",")
}
